/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gpaglia_bluetooth_lescan_impl_ScannerImpl */

#ifndef _Included_com_gpaglia_bluetooth_lescan_impl_ScannerImpl
#define _Included_com_gpaglia_bluetooth_lescan_impl_ScannerImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gpaglia_bluetooth_lescan_impl_ScannerImpl
 * Method:    openDeviceFromAddress
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gpaglia_bluetooth_lescan_impl_ScannerImpl_openDeviceFromAddress
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_gpaglia_bluetooth_lescan_impl_ScannerImpl
 * Method:    openDeviceFromName
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gpaglia_bluetooth_lescan_impl_ScannerImpl_openDeviceFromName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_gpaglia_bluetooth_lescan_impl_ScannerImpl
 * Method:    openDeviceFromDevNo
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_gpaglia_bluetooth_lescan_impl_ScannerImpl_openDeviceFromDevNo
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
